MemoryGame/Models/IconViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MemoryGame.Models
{
    public class IconViewModel
    {
        public List<string> InitIcons { get; set; }
        public List<string> AllIcons { get; set; }
    }
}

MemoryGame/Controllers/GameController.cs
using MemoryGame.Helpers;
using MemoryGame.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;

namespace MemoryGame.Controllers
{
    public class GameController : Controller
    {

        private readonly IIconHelper _iconHelper;
        private readonly IIconPostHelper _iconPostHelper;
        private readonly INumbersHelper _numbersHelper;

        public GameController(IIconHelper iconHelper, INumbersHelper numbersHelper, IIconPostHelper iconPostHelper)
        {
            _iconHelper = iconHelper;
            _numbersHelper = numbersHelper;
            _iconPostHelper = iconPostHelper;
        }

        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult Numbers()
        {
            var level = 0;

            var currentLevel = HttpContext.Session.GetString("Level");
            if (string.IsNullOrEmpty(currentLevel))
            {
                HttpContext.Session.SetString("Level", "1");
                level = 1;
            }
            else
            {
                level = Convert.ToInt32(currentLevel);
            }

            var model = _numbersHelper.GetRandomNumberFromRange(level);

            HttpContext.Session.SetString("Number", model.ToString());

            return View(model);
        }


        [HttpPost]
        public IActionResult NumbersPost(int answer)
        {
            var number = Convert.ToInt32(HttpContext.Session.GetString("Number"));

            if (answer == number)
            {
                var currentLevel = Convert.ToInt32(HttpContext.Session.GetString("Level"));
                currentLevel++;
                HttpContext.Session.SetString("Level", currentLevel.ToString());

            }

            return RedirectToAction("Numbers");
        }


        public IActionResult Icons()
        {

            var iconlevel = 0;

            var currentLevel = HttpContext.Session.GetString("IconLevel");
            if (string.IsNullOrEmpty(currentLevel))
            {
                HttpContext.Session.SetString("IconLevel", "1");
                iconlevel = 1;
            }
            else
            {
                iconlevel = Convert.ToInt32(currentLevel);
            }

            int numberOfAnswers = iconlevel + 3;
            int numberOfIcons = numberOfAnswers * 2;
            
            IconViewModel model = new IconViewModel {AllIcons = _iconHelper.GetIcons(numberOfIcons) };

            model.InitIcons = model.AllIcons.Take(numberOfAnswers).ToList();

            var str = JsonConvert.SerializeObject(model.InitIcons);
            HttpContext.Session.SetString("Answers", str);

            var rnd = new Random();

            model.AllIcons = model.AllIcons.OrderBy(item => rnd.Next()).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult IconsPost(List<string> values)
        {

            var str = HttpContext.Session.GetString("Answers");
            var answers = JsonConvert.DeserializeObject<List<string>>(str);

            var userAnswers = _iconPostHelper.FormatIconText(values);

            var result = answers.OrderBy(i => i).SequenceEqual(userAnswers.OrderBy(i => i));

            if (result)
            {
                var currentLevel = Convert.ToInt32(HttpContext.Session.GetString("IconLevel"));
                currentLevel++;
                HttpContext.Session.SetString("IconLevel", currentLevel.ToString());
            }

            return RedirectToAction("Icons");
        }
    }
}

MemoryGame/Views/Game/Icons.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@model MemoryGame.Models.IconViewModel

@{
    ViewBag.Title = "Icons";
    Layout = "_Layout";
}

<h2>Icons</h2>

<div>Cuerrent level: <strong>@HttpContextAccessor.HttpContext.Session.GetString("IconLevel")</strong></div>

<div id="initialDisplay">
    <p>Remember the following Icons:</p>
    <div>
        @foreach (var item in Model.InitIcons)
        {
            <i class="fa @item fa-5x"></i>
        }
    </div>
    
    <div id="countdown"></div>
</div>
    

<div id="answerDisplay">
    <p>Select Icons:</p>
    @foreach (var item in Model.AllIcons)
    {
        <i class="fa @item fa-5x"></i>
    }

    <div><button class="btn btn-success" id="submit">Submit</button></div> 
</div>

@section Scripts
{

    <script src="~/js/jquery.countdown360.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        $(function () {

            var answers = [];

            $("#answerDisplay i").on("click",
                function () {
                    $(this).toggleClass('selected');
                });

            $("#submit").on("click",
                function () {

                    $("#answerDisplay i").each(function () {
                        if ($(this).hasClass("selected")) {
                            answers.push($(this).attr("class"));
                        }
                    });

                    var postData = { values: answers };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("IconsPost")',
                        data: postData,
                        success: function() {
                            window.location.href = '@Url.Action("Icons", "Game")';
                        },
                        error: function() {
                            window.location.href = '@Url.Action("Icons", "Game")';
                        },
                        dataType: "json",
                        traditional: true
                    });
                });


            $("#answerDisplay").hide();

            $("#countdown").countdown360({
                radius: 60,
                seconds: 10,
                fontColor: '#FFFFFF',
                autostart: false,
                onComplete: function() {
                    $("#initialDisplay").hide();
                    $("#answerDisplay").show();
                }
            }).start();
        });

    </script>
}

MemoryGame/Views/Game/Menu.cshtml
@{
    ViewBag.Title = "Numbers";
    Layout = "_Layout";
}

<h2>Index</h2>
<div id="MenuBlock">
    <a asp-area="" asp-controller="Game" asp-action="Numbers" class="btn btn-success">Numbers</a>
    <a asp-area="" asp-controller="Game" asp-action="Icons" class="btn btn-success">Icons</a>
</div>

MemoryGame/Views/Game/Numbers.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@model int

@{
    ViewBag.Title = "Numbers";
    Layout = "_Layout";
}

<h2>Numbers</h2>

<div>Cuerrent level: <strong>@HttpContextAccessor.HttpContext.Session.GetString("Level")</strong></div>

<div id="initialDisplay">
    <p>Remember the following number:</p>
    
    <h2><strong>@Model</strong></h2>

    <div id="countdown"></div>
</div>

<div id="answerDisplay">
    <form asp-controller="Game" asp-action="NumbersPost" method="post">
        <div class="form-group">
            <label for="answer">Answer:</label>
            <input type="text" class="form-control" name="answer" id="answer">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>


@section Scripts
{

    <script src="~/js/jquery.countdown360.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        $(function () {

            $("#answerDisplay").hide();

            $("#countdown").countdown360({
                radius: 60,
                seconds: 10,
                fontColor: '#FFFFFF',
                autostart: false,
                onComplete: function() {
                    $("#initialDisplay").hide();
                    $("#answerDisplay").show();
                }
            }).start();
        });
        
    </script>
}

MemoryGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemoryGame</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Game" asp-action="Menu" class="navbar-brand">MemoryGame</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Game" asp-action="Numbers">Numbers</a></li>
                    <li><a asp-area="" asp-controller="Game" asp-action="Icons">Icons</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MemoryGame</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>